//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComprobación
    {
        public tblComprobación()
        {
            this.tblComprobacionGastos = new tblComprobacionGastos();
            this.tblGastosSinComprobar = new tblGastosSinComprobar();
            this.tblTotalDiario = new tblTotalDiario();
            this.tblTotalGastos = new tblTotalGastos();
        }
    
        public int Idcomprobacion { get; set; }
        public int IdSolicitud { get; set; }
        public string IdProyecto { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime fecha { get; set; }
        public string gerenteAdmin { get; set; }
        public string jefeInmediato { get; set; }
        public string areaContable { get; set; }
    
        public tblSolicitudV tblSolicitudV { get; set; }
        public tblComprobacionGastos tblComprobacionGastos { get; set; }
        public tblGastosSinComprobar tblGastosSinComprobar { get; set; }
        public tblTotalDiario tblTotalDiario { get; set; }
        public tblTotalGastos tblTotalGastos { get; set; }
    }
    public class ComprobacionDTO
    {
        public int IdSolicitud { get; set; }
        public string IdProyecto { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime fecha { get; set; }
        public string gerenteAdmin { get; set; }
        public string jefeInmediato { get; set; }
        public string areaContable { get; set; }

        public int  tblSolicitudV { get; set; }
        public IEnumerable<tblComprobacionGastos> tblComprobacionGastos { get; set; }
        public IEnumerable<tblGastosSinComprobar> tblGastosSinComprobar { get; set; }
        public IEnumerable<tblTotalDiario> tblTotalDiario { get; set; }
        public IEnumerable<tblTotalGastos> tblTotalGastos { get; set; }
    }
}
