//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGastosSinComprobar
    {
        public tblGastosSinComprobar()
        {
            this.tblRelacionGastos = new tblRelacionGastos();
        }
    
        public int IdGastosSinComprobar { get; set; }
        public int IdComprobacion { get; set; }
        public string IdProyecto { get; set; }
        public System.DateTime fecha { get; set; }
        public double cantidad { get; set; }
        public string cantidadLetra { get; set; }
        public string destino { get; set; }
        public System.DateTime fechaComision { get; set; }
        public string jefeInmediato { get; set; }
        public string admonFinanzas { get; set; }
        public string tipoComprobacion { get; set; }
    
        public  tblComprobación tblComprobación { get; set; }
        public  tblProyecto tblProyecto { get; set; }
        public  tblRelacionGastos tblRelacionGastos { get; set; }
    }
    public class GastosSinComprobarDTO
    {
        public int IdComprobacion { get; set; }
        public string IdProyecto { get; set; }
        public System.DateTime fecha { get; set; }
        public double cantidad { get; set; }
        public string cantidadLetra { get; set; }
        public string destino { get; set; }
        public System.DateTime fechaComision { get; set; }
        public string jefeInmediato { get; set; }
        public string admonFinanzas { get; set; }
        public string tipoComprobacion { get; set; }

        public int tblComprobación { get; set; }
        public int tblProyecto { get; set; }
        public IEnumerable<tblRelacionGastos> tblRelacionGasto { get; set; }
 
    }
}
