//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyecto
    {
        public tblProyecto()
        {
            this.tblGastosSinComprobar = new HashSet<tblGastosSinComprobar>();
            this.tblPersonasAsignadas = new HashSet<tblPersonasAsignadas>();
            this.tblSolicitudV = new HashSet<tblSolicitudV>();
        }
    
        public string IdProyecto { get; set; }
        public string nombre { get; set; }
        public Nullable<double> montoDesayuno { get; set; }
        public Nullable<double> montoComida { get; set; }
        public Nullable<double> montoCena { get; set; }
        public string nombreGerente { get; set; }
        public string nombreJefe { get; set; }
        public string nombreConta { get; set; }
    
        public virtual ICollection<tblGastosSinComprobar> tblGastosSinComprobar { get; set; }
        public virtual ICollection<tblPersonasAsignadas> tblPersonasAsignadas { get; set; }
        public virtual ICollection<tblSolicitudV> tblSolicitudV { get; set; }
    }
}
