//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonasAsignadas
    {
        public tblPersonasAsignadas()
        {
            this.tblSolicitudV = new tblSolicitudV();
        }
    
        public string IdProyecto { get; set; }
        public int IdPersonas { get; set; }
    
        public  tblProyecto tblProyecto { get; set; }
        public tblSolicitudV tblSolicitudV { get; set; }
    }
    public class PersonasAsignadas
    {
        public string IdProyecto { get; set; }
        
        public int  tblProyecto { get; set;}
        public IEnumerable<tblSolicitudV> tblSolicitudV { get; set; }

    }

}
