//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudV
    {
        public tblSolicitudV()
        {
            this.tblAlimentos = new HashSet<tblAlimentos>();
            this.tblComprobación = new HashSet<tblComprobación>();
            this.tblHospedaje = new HashSet<tblHospedaje>();
            this.tblOtrosGastos = new HashSet<tblOtrosGastos>();
            this.tblTransporte = new HashSet<tblTransporte>();
            this.tblPersonasAsignadas = new HashSet<tblPersonasAsignadas>();
        }
    
        public int IdSolicitud { get; set; }
        public int IdEmpleado { get; set; }
        public string IdProyecto { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public string destino { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.DateTime> fechaRegreso { get; set; }
        public string horaSalida { get; set; }
        public string horaRegreso { get; set; }
        public double monto { get; set; }
        public string numCuenta { get; set; }
        public string cantLetra { get; set; }
        public int totalDias { get; set; }
        public double totalGasto { get; set; }
    
        public virtual ICollection<tblAlimentos> tblAlimentos { get; set; }
        public virtual ICollection<tblComprobación> tblComprobación { get; set; }
        public virtual tblEmpleado tblEmpleado { get; set; }
        public virtual ICollection<tblHospedaje> tblHospedaje { get; set; }
        public virtual ICollection<tblOtrosGastos> tblOtrosGastos { get; set; }
        public virtual tblProyecto tblProyecto { get; set; }
        public virtual ICollection<tblTransporte> tblTransporte { get; set; }
        public virtual ICollection<tblPersonasAsignadas> tblPersonasAsignadas { get; set; }
    }
}
