//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTotalDiario
    {
        public int IdComprobacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public Nullable<double> totalConceptoGen { get; set; }
    
        public tblComprobación tblComprobación { get; set; }
    }
    public class TotalDiarioDTO
    {
        public int IdComprobacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public Nullable<double> totalConceptoGen { get; set; }
    }
}
