//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTotalGastos
    {
        public int IdComprabacion { get; set; }
        public Nullable<double> boletos { get; set; }
        public Nullable<double> otrosGastos { get; set; }
        public System.DateTime fecha { get; set; }
        public double totalViaje { get; set; }
        public Nullable<double> totalSinComprobar { get; set; }
        public double saldo { get; set; }
    
        public tblComprobación tblComprobación { get; set; }
    }

    public class TotalGastosDTO
    {
        public int IdComprabacion { get; set; }
        public Nullable<double> boletos { get; set; }
        public Nullable<double> otrosGastos { get; set; }
        public System.DateTime fecha { get; set; }
        public double totalViaje { get; set; }
        public Nullable<double> totalSinComprobar { get; set; }
        public double saldo { get; set; }
    }
}
