//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransporte
    {
        public int IdSolicitud { get; set; }
        public string conceptoo { get; set; }
        public double total { get; set; }
        public int numTransporte { get; set; }
    
        public tblSolicitudV tblSolicitudV { get; set; }
    }

    public class TransporteDTO
    {
        public int IdSolicitud { get; set; }
        public string conceptoo { get; set; }
        public double total { get; set; }
        public int numTransporte { get; set; }
    }
}
